name: ci

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: RelWithDebInfo
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-11]
        cc: [gcc-11]

    steps:
      - uses: actions/checkout@v2
      - name: Dependency setup
        run: |
            echo "EU_CONAN_PROFILE=.github/eu_conan_profile.toml" >> $GITHUB_ENV
            sudo apt update
            sudo apt install gcc-11 g++-11 ninja-build
			pip3 install --force-reinstall -v "conan==1.60.1"
            CXX=g++-11 CC=gcc-11 make dep-setup
      - name: Configure
        shell: bash
        working-directory: ${{github.workspace}}
        run: make config

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
            make build
      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: make clean-test

      - name: Benchmarks
        working-directory: ${{github.workspace}}
        shell: bash
        run: make clean-bench
